name: Bug report
description: Report a problem with the extension
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Short, clear summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce it?
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happens?
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser + version
      placeholder: Chrome 123
    validations:
      required: true
  - type: input
    id: extension
    attributes:
      label: Extension version
      placeholder: 0.1.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Console logs or screenshots (if any)
